# Generated by Django 2.2 on 2019-04-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='user',
        ),
    ]
